- name: install-jdk
  hosts: localhost
  vars:
    java_download_url: http://www.kwangsiklee.com/wp-content/uploads/direct/jdk-8u181-linux-x64.tar.gz
    java_archive_name: jdk-8u181-linux-x64.tar.gz
    java_root_dir: /usr/share/java-1.8.0
    java_jdk_dir: "{{ java_root_dir }}/jdk1.8.0_181"

  tasks:
    - name: Check if Java has already been downloaded and unpacked
      stat:
        path: '{{ java_jdk_dir }}'
      register: dir

    - name: download official binary
      get_url:
        url: "{{ java_download_url }}"
        mode: 0755
        force: no
        dest: /tmp/{{ java_archive_name }}
      when: dir.stat.exists == False
      tags:
        - java_install


    - name: Create Java directory
      file:
        name: "{{ java_root_dir }}"
        state: directory
      when: dir.stat.exists == False
      tags:
        - java_install

    # Untar the downloaded Java archive. The owner and group must be set otherwise the folder
    # structure is created using numerical values for these.
    - name: Unpack Java JDK
      unarchive:
        src: /hanmail/repo/bigdata-ansible/jdk/{{ java_archive_name }}
        dest: "{{ java_root_dir }}"
        copy: no
        owner: root
        group: root
      when: dir.stat.exists == False
      tags:
        - java_install

    # Use the alternatives command to install the appropriate links to the executables in the PATH.
    # Alternatives allows multiple versions of Java to be installed with the correct executable
    # on the PATH being used.
    - name: Install Java alternatives
      alternatives:
        name: java
        link: /usr/bin/java
        path: '{{ java_jdk_dir }}/bin/java'
      tags:
        - java_install_alternatives

    # Cleanup install by deleting downloaded Java archive
    - name: Delete Java JDK tar.gz file
      file:
        path: /tmp/{{ java_archive_name }}
        state: absent
      tags:
        - java_cleanup

    # Set Ansible fact that Java has completed installation. This is so that this role can be used in
    # other dependent roles. Those roles can check for this fact to determine whether or not this role
    # should be run. Failing to do so will mean that this role is executed even if it has already been run.
    - name: Set fact java_8_installed
      set_fact:
        java_8_installed: true
      tags:
        - java_install
