- module: system
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
  period: 1m

#- module: system
#  metricsets:
#    - core
#    - diskio
#    - socket

- module: system
  period: 5m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime

- module: system
  period: 5m
  metricsets: ["diskio"]
  diskio.include_devices: []

#- module: system
#  period: 5m
#  metricsets:
#    - raid
#  raid.mount_point: '/'
