- name: install-filebeat
  hosts: localhost
  vars:
    filebeat_binary_path: ~/filebeat
    filebeat_version: 6.3.2

  tasks:
    - name : create filebeat directory
      file:
        path:  "{{ filebeat_binary_path }}"
        state: directory

    - name : create filebeat binary directory
      file:
        path:  "{{ filebeat_binary_path }}/binary"
        state: directory

    - name : delete filebeat directory
      file:
        path: "{{ filebeat_binary_path }}/filebeat-{{filebeat_version}}"
        state: absent

    - name : delete script directory
      command: "rm -rf {{ filebeat_binary_path }}/script"

    - name: download official filebeat binary
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{filebeat_version}}-linux-x86_64.tar.gz"
        dest: "{{ filebeat_binary_path }}/binary"
        mode: 0755
        force: no

    - name : extract filebeat binary
      unarchive:
        src: "{{filebeat_binary_path}}/binary/filebeat-{{filebeat_version}}-linux-x86_64.tar.gz"
        dest: "{{ filebeat_binary_path }}"

    - name: "synchronize filebeat config"
      synchronize:
        src: "../filebeat/{{filebeat_version}}/filebeat.yml"
        dest: "{{ filebeat_binary_path }}/filebeat-{{filebeat_version}}/filebeat.yml"