# This is an revised configuration for Docker Compose by Jack Lee.
version: '2'
services:
  server:
#    image: lks21c/redash:5.0.0-beta
    image: lks21c/redash:4.0.1
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
      REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.oracle,redash.query_runner.python
      LD_LIBRARY_PATH: /usr/lib/oracle/12.2/client64/lib/
      ORACLE_HOME: /usr/lib/oracle/12.2/client64
      LANG: "en_US.UTF-8"
      NLS_LANG: "AMERICAN_AMERICA.AL32UTF8"
    restart: always
  worker:
#    image: lks21c/redash:5.0.0-beta
    image: lks21c/redash:4.0.1
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_ADDITIONAL_QUERY_RUNNERS: redash.query_runner.oracle,redash.query_runner.python
      LD_LIBRARY_PATH: /usr/lib/oracle/12.2/client64/lib/
      ORACLE_HOME: /usr/lib/oracle/12.2/client64
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
      C_FORCE_ROOT: "true"
      LANG: "en_US.UTF-8"
      NLS_LANG: "AMERICAN_AMERICA.AL32UTF8"
    restart: always
  redis:
    image: redis:3.0-alpine
    # restart: always
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - /opt/postgres-data:/var/lib/postgresql/data # left path is hosts's directory.
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "8484:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
