apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redashserver-deploy
  name: redashserver-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: redashserver-deploy
    spec:
      containers:
      - args:
        - server
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: REDASH_COOKIE_SECRET
          value: veryverysecret
        - name: REDASH_DATABASE_URL
          value: postgresql://postgres@postgres-svc/postgres
        - name: REDASH_LOG_LEVEL
          value: INFO
        - name: REDASH_REDIS_URL
          value: redis://redis-svc:6379/0
        - name: REDASH_WEB_WORKERS
          value: "4"
        - name: REDASH_ADDITIONAL_QUERY_RUNNERS
          value: redash.query_runner.oracle,redash.query_runner.python
        - name: LD_LIBRARY_PATH
          value: /usr/lib/oracle/12.2/client64/lib/
        - name: ORACLE_HOME
          value: /usr/lib/oracle/12.2/client64
        - name: LANG
          value: "en_US.UTF-8"
        - name: NLS_LANG
          value: "AMERICAN_AMERICA.AL32UTF8"

        image: lks21c/redash:5.0.1
        name: redashserver-deploy
        ports:
        - containerPort: 5000
      restartPolicy: Always
